# Coding
- The Schrödinger equation $\mathrm{i}\dot{\psi}(t) = H \psi(t)$ with a constant Hamiltonian matrix $H$ has the solution $\psi(t) = U(t) \psi(0)$, where $U(t) = \exp(-\mathrm{i} H t)$ is called the propagator. Write a function that computes the propagator for any given Hamiltonian matrix. (Hint: What's the form of $U$ in the energy basis?)

- Use `scipy.optimize.root()` to implement a function that computes the inverse of an arbitrary square matrix. (Hint: Solve $X$ from $A X = I$ for given matrix $A$.)

$\textbf{Theory:}$

$  A|\phi_{i} \rangle=a_i|\phi_i\rangle $ and the eigenvectors of A form a complete orthonormal set —
that is to say, $$\sum_{i}|\phi_i\rangle \langle\phi_i|=I$$ then operator can be reconstructed in a useful diagonal form in terms of its eigenvalues and eigenvectors as $$
A=\sum_i{a_i |\phi_i\rangle \langle \phi_i|}\tag{1}$$

One can use the diagonal representation to define a function of an operator, $$f(A)=\sum_i{f(a_i) |\phi_i\rangle \langle \phi_i|}\tag{2}$$

In [199]:
import numpy as np
import numpy.linalg as la

In [200]:
H = np.array([[2, 2, 4], 
              [1, 3, 5],
              [2, 3, 4]])
#w,v=la.eig(H)
print('Eigen values:', w)
print('Eigen vectors:', v)

Eigen values: [ 8.80916362  0.92620912 -0.73537273]
Eigen vectors: [[-0.52799324 -0.77557092 -0.36272811]
 [-0.604391    0.62277013 -0.7103262 ]
 [-0.59660259 -0.10318482  0.60321224]]


In [201]:
w  #eigenvalue

array([ 8.80916362,  0.92620912, -0.73537273])

In [202]:
v  #eigen vector

array([[-0.52799324, -0.77557092, -0.36272811],
       [-0.604391  ,  0.62277013, -0.7103262 ],
       [-0.59660259, -0.10318482,  0.60321224]])

In [203]:
#extract ith column

v[:,0] #1st column, first eigen vector

array([-0.52799324, -0.604391  , -0.59660259])

In [204]:
v[:,1] #2nd column, second eigen vector

array([-0.77557092,  0.62277013, -0.10318482])

In [205]:
v[:,2] #3rd column, third eigen vector

array([-0.36272811, -0.7103262 ,  0.60321224])

In [206]:
#Checking orthonormalilty

np.sum(v[:,0]*v[:,1]) #close to zero

0.09465987213763337

In [207]:
np.sum(v[:,0]*v[:,0].T)  #so eigen vectors are orthogonal, form orthonormal basis

1.0000000000000002

In [208]:
#Def function for prpagtor U(t)=exp(-iHt):

def U(H,t):
    w,v=la.eig(H)
    
    #spectral decomposition of H
    H_1=w[0]*np.sum(v[:,0]*v[:,0].T)+w[1]*np.sum(v[:,1]*v[:,1].T)+w[2]*np.sum(v[:,2]*v[:,2].T)
    #operating exp function on eigen values of H 
    U=np.exp(1j*-w[0]*t)*np.sum(v[:,0]*v[:,0].T)+np.exp(1j*-w[1]*t)*np.sum(v[:,1]*v[:,1].T)+np.exp(-1j*w[2]*t)*np.sum(v[:,2]*v[:,2].T)
    return U

In [209]:
H = np.array([[2, 2, 4], [1, 3, 5],[2, 3, 4]]) # any symmetric matrix

t=1   #arbitrary time

In [210]:
U(H,t)

(0.5260304374790282-0.7059444475348868j)